#!/bin/bash

# Read hosts
mapfile hosts < hosts

# Decimal to binary netmask converter
function decimal2binary {

	readonly local d2b=({0,1}{0,1}{0,1}{0,1}{0,1}{0,1}{0,1}{0,1})
	local binary=
	local ip=$1

	# Extract decimals
	while [[ $ip =~ [[:digit:]]{1,3} ]]; do
		# Convert decimal to binary and append to result
		binary+=${d2b[$BASH_REMATCH]}
		
		# Remove the match from current search
		ip=${ip/$BASH_REMATCH//}
	done

	echo $binary
}

# Extract IPs and netmasks and initialise nodes
declare -A nodes
declare -A netmasks

for (( i=0; i<${#hosts[*]}; ++i )); do
	# Does entry match an IP?
	if [[ ${hosts[i]} =~ ^[[:digit:]\.]{7,} ]]; then
		nodes[$BASH_REMATCH]=unknown
	else
		# Does line match a CIDR netmask?
		[[ ${hosts[i]} =~ ([[:digit:]\.]{7,})/([[:digit:]]{2}) ]] && netmasks[${BASH_REMATCH[1]}]=${BASH_REMATCH[2]}
	fi
done

# Iterate through the netmasks and compare them to each ip
for netmask in ${!netmasks[*]}; do
	# Convert netmask
	netmask_binary=$(decimal2binary $netmask)

	# Trim off host identifier
	width=${netmasks[$netmask]}
	netmask_binary=${netmask_binary:0:$width}

	for ip in ${!nodes[*]}; do
		host_binary=$(decimal2binary $ip)
		[[ $host_binary =~ ^$netmask_binary ]] && nodes[$ip]=$netmask
	done
done

# Header
dot+=$(echo "graph { node [style=filled]; node [fillcolor=red];")

# Dump netmasks
for netmask in ${!netmasks[*]}; do dot+=$(echo -e "\t\"$netmask\" [fillcolor=cyan];"); done

# Dump node info
for node in ${!nodes[*]}; do dot+=$(echo -e "\t\"$node\" [fillcolor=white];"); done

# Dump connections
for node in ${!nodes[*]}; do dot+=$(echo -e "\t\"$node\" -- \"${nodes[$node]}\";"); done

# Footer
dot+=$(echo "}")

# Generate topology
circo -T png > topology.png <<< $dot
