#!/bin/bash

base=..

# Clean and make
for dir in $base/*
do
	if [[ -d $dir ]]
	then
		echo
		echo -e $(basename $dir)

		pushd $dir > /dev/null
		if [[ -e Makefile ]]
		then
			make -j clean
			make -j
		else
			echo Nothing to build
		fi
		popd > /dev/null
	fi
done

# Run cppcheck
cppcheck $base

# echo regress
