#!/bin/bash

# Clean and make
for dir in *
do
	if [[ -d $dir ]]
	then
		project=$(basename $dir)

		pushd $dir > /dev/null
		if [[ -e makefile ]]
		then
			make cppcheck
			make -j clean > /dev/null
			make -j > /dev/null && echo $project OK || echo $project FAIL
		else
			echo $project nothing to build
		fi
		popd > /dev/null
	fi
done

# echo regress
