include ../rules.mak
FLAGS+=-I../pxl
LFLAGS=-lncurses

run: foo
	./foo < /usr/lib/libreoffice/share/gallery/sounds/kling.wav

run2: foo
	./foo  < ~//Desktop/uploads/Logic\ 7/2006/Alive/Audio\ Files/aliveapella.wav

run3: foo
	./play_all
