#!/bin/bash

# Mapfile
mapfile array < hosts

# Entries in array
echo entries ${#array[*]}

# This prints every word
for line in ${array[*]}; do
	echo $line
done

IFS=$'\n'
# This prints every _line_
for line in ${array[*]}; do
	echo $line
done
unset IFS
