#!/bin/bash

# Create associative array of hosts
declare -A hosts
hosts=(
[192.168.109.1]=unknown
[192.168.109.2]=unknown
[192.168.109.3]=unknown
[192.168.109.4]=unknown
[192.168.109.5]=unknown
[192.168.109.7]=unknown
[192.168.109.8]=unknown
[10.226.0.1]=unknown
[10.226.0.2]=unknown
[10.226.1.3]=unknown
[192.168.109.6]=unknown
[10.226.0.4]=unknown
)

# Known subnets
declare -A masks
masks=(
[192.168.109]=foonet
[10.226.0]=barnet
)

# Header
cat <<!
graph
{
	node [style=filled fillcolor=cyan]

!

# Examine hosts
for ip in ${!hosts[*]}
do
	echo -e \\n$ip

	# Test each mask
	for mask in ${!masks[*]}
	do
		echo try $mask
		# Stash mask name if the ip matches and stop search
		if [[ $ip =~ $mask ]]
		then
			echo match $BASH_REMATCH

			hosts[$ip]=${masks[$mask]}

			echo stash ${hosts[$ip]}

			break
		else
			echo no match
		fi
	done
done

# Dump connections
: <<!
for ip in ${!hosts[@]}
do
	echo -e "\t\"$ip\" -- \"${hosts[ip]}\""
done

# Footer
cat <<!

	// $(date)
}
!
