#!/bin/bash

# Create array of hosts
hosts=(
192.168.109.1
192.168.109.2
192.168.109.3
192.168.109.4
192.168.109.5
192.168.109.7
192.168.109.8
10.226.0.1
10.226.0.2
10.226.0.3
192.168.109.6
)

mask=192.168.109

# Header
cat <<!
graph
{
	node [style=filled fillcolor=grey shape=box]

!

# Examine hosts
for ip in ${hosts[@]}
do
	if [[ $ip =~ $mask ]]
	then
		echo -e "\t\"$ip\" -- \"$mask\""
	else
		echo -e "\t\"$ip\" -- unknown"
	fi
done

# Footer
cat <<!

	// $(date)
}
!
