#!/bin/bash

waypoints='ee.co.uk google.co.uk bbc.co.uk'

for w in $waypoints
do
	tpath=$(traceroute -n -m 13 $w)

	# Extract the IPs
	while [[ $tpath =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]
	do
		IPs+=($BASH_REMATCH)

		# Remove the current match
		tpath=${tpath/$BASH_REMATCH//}
	done

	# Format for yUML
	for (( i = 0; i < ${#IPs[@]} - 1; ++i ))
	do
		echo "[${IPs[$i]}]-[${IPs[$i + 1]}]"
	done
done
