#!/bin/bash

maxhops=13
tpath=$(traceroute -n -m $maxhops ee.co.uk)

# Extract the IPs
while [[ $tpath =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]
do
	IPs+=($BASH_REMATCH)

	# Remove the current match
	tpath=${tpath/$BASH_REMATCH//}
done

# Format for yUML
for (( i = 0; i < ${#IPs[@]} - 1; ++i ))
do
	echo "[${IPs[$i]}]-[${IPs[$i + 1]}]"
done

