#!/bin/bash

# MIME type
cat <<MIME
Content-type: text/plain

MIME

mapfile hosts < simple.svg

for line in ${hosts[@]}
do
	[[ $line =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] && echo $BASH_REMATCH
done
