#!/bin/bash

# Set MIME type
cat <<MIME
Content-type:text/plain

MIME

# Read hosts line by line
while read line
do
	# Check if it starts with a IP
	if [[ $line =~ ^[0-9.]+ ]]
	then
		[[ $(ping -w 1 -c 1 $BASH_REMATCH | grep '1 received') != "" ]] && tput setaf 2 || tput setaf 1
	else
		tput sgr0
	fi

	echo $line
done < hosts

# Reset colours
tput sgr0
