#!/bin/bash

cat <<MIME
Content-type:text/plain

MIME

date

IFS=$'\n'
lines=($(cat hosts))

echo ${#lines[*]} lines in host file

for line in ${lines[*]}
do
	IP=$(echo $line | cut -d' ' -f1)
	# echo -en "$line\t"
	ping -w 1 -c 1 $IP 2>/dev/null | grep '1 received' && echo good || echo bad

	# echo $line
done
